Прикрепляю 0 задание
teststudent311/DBMS_Task1 pull request #1
Opened 2022-09-12 09:05 UTC by teststudent311

Задание:
1. Пользователь вводит размер одномерного массива size.
2. Происходит создание одномерного массива values элементов типа doubleразмерности size, заполненного псевдослучайными значениями.
3. Вывод созданного массива на экран.
4. Выполнение алгоритма avg над созданным массивом.
5. Вывод результата применения алгоритма на экран.

2022-09-16 14:34 UTC, teststudent311 commented
Марина Алексеевна, я добавил изменения в код согласно вашим рекомендациям.

2022-09-19 12:09 UTC, MarinaPaley requested changes

2022-09-19 12:09 UTC, MarinaPaley commented on dbms1.cpp
> +	return (size_t) value;
`return static_cast<size_t>(value);` - это приведение в стиле C++, а ваше в стиле C.

2022-09-19 12:09 UTC, MarinaPaley commented on dbms1.cpp
> +double* createArray(size_t size)
Если параметры функции не изменяются, то они явно должны быть обозначены `const`
[By Alex Allain](https://www.cprogramming.com/tutorial/const_correctness.html)
>The const keyword allows you to specify whether or not a variable is modifiable. You can use const to prevent modifications to variables and const pointers and const references prevent changing the data pointed to (or referenced).
>Const дает вам возможность более четко документировать вашу программу и фактически обеспечивать соблюдение этой документации. Ключевое слово const обеспечивает вашим пользователям гарантии, позволяющие оптимизировать производительность без угрозы повреждения их данных, обеспечивая соблюдение вашей документации. Например, константные ссылки позволяют указать, что упомянутые данные не будут изменены; это означает, что вы можете использовать константные ссылки как простой и немедленный способ повышения производительности для любой функции, которая в настоящее время принимает объекты по значению, не беспокоясь о том, что ваша функция может изменить данные. Даже если это произойдет, компилятор предотвратит компиляцию кода и предупредит вас о проблеме. С другой стороны, если бы вы не использовали константные ссылки, у вас не было бы простого способа гарантировать, что ваши данные не были изменены.

`const size_t size`

2022-09-19 12:09 UTC, MarinaPaley commented on dbms1.cpp
> +		array[i] = rand();
[Бьярне Страуструп](https://ru.wikipedia.org/wiki/Страуструп,_Бьёрн) в своей [книге](https://www.stroustrup.com/tour2.html) даёт советы [1, стр.&nbsp;269]:
>[5] Для получения генератора случайных чисел свяжите генератор с распределением; &sect;14.5.
>[6] Следите, чтобы ваши случайные числа были достаточно случайными; &sect;14.5.
>[7] Не используйте `rand()` из стандартной библиотеки C; для серьезного применения этот генератор недостаточно случаен; &sect;14.5.

Также Страуструп [1, стр.&nbsp;265&ndash;267] равёрнуто поясняет необходимость использования генератора случайных чисел и приводит примеры кода, особо обращая внимание на использование заголовочного файла [`<random>`](https://en.cppreference.com/w/cpp/numeric/random).

[1] **Страуструп, Бьярне** Язык программирования C++. Краткий курс, 2-е изд. : Пер. с англ. &mdash; СПб. : ООО&nbsp;"Диалектика", 2019. &mdash; 320 с. : ил. &mdash; Парал. тит. англ.

ссылка на код в Тимсе

2022-09-19 12:09 UTC, MarinaPaley commented on dbms1.cpp
> +	if (array == nullptr) return (double) 0;
Не замалчивайте ошибку, выбрасывайте исключение!

2022-09-19 12:09 UTC, MarinaPaley commented on dbms1.cpp
> +	if (array == nullptr) return;
Выбрасывайте исключение!

2022-09-25 20:03 UTC, teststudent311 commented
Внёс корректировки в код.

2022-09-26 15:15 UTC, MarinaPaley requested changes

2022-09-26 15:15 UTC, MarinaPaley commented on dbms1.cpp
> +	if (array == nullptr)
Массив необходимо удалять следующим безопасным способом
```cpp
if (array != nullptr)
{
   delete[] array;
   array = nullptr;
}
```

2022-09-26 16:32 UTC, MarinaPaley approved these changes

2022-09-29 10:50 UTC, merged